---
title: "HDI Dataset Cleaning"
author: "Group Kable"
output: html_document
---

# Global Options and Loading Packages

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache=TRUE, 
                      messages=FALSE, 
                      warning=FALSE)
library(tidyverse)
library(readxl)
library(readr)
library(haven)
```


# Reading the data by renaming the columns 

```{r}
read_data <- function(x,y,z){read_excel("data/2020_Statistical_Annex_Table_1.xlsx",
                                        rang = x,col_names = FALSE) %>% 
    rename(HDI_rank_2019 = ...1, Country = ...2, 
           HDI_Value = ...3, 
           Life_expectancy = ...5, 
           Expected_years_of_schooling = ...7, 
           Mean_years_of_schooling = ...9, 
           GNI_per_capita = ...11, 
           GNI_rank_minus_HDI_rank = ...13, 
           HDI_rank_2018 = ...15)} %>% 
  select(HDI_rank_2019, Country, HDI_Value, Life_expectancy, Expected_years_of_schooling, Mean_years_of_schooling, GNI_per_capita, GNI_rank_minus_HDI_rank, HDI_rank_2018) %>% 
  mutate(y = z )
```


# Selecting four parts of the dataset and binding into one.

```{r}
VERY_HIGH_HUMAN_DEVELOPMENT <- read_data('A9:O74',Degree_of_Human_Development, 'VERY HIGH HUMAN DEVELOPMENT')
HIGH_HUMAN_DEVELOPMENT <- read_data('A76:O128', Degree_of_Human_Development, 'HIGH HUMAN DEVELOPMENT' ) 
MEDIUM_HUMAN_DEVELOPMENT <- read_data('A130:O166', Degree_of_Human_Development, 'MEDIUM HUMAN DEVELOPMENT' ) 
LOW_HUMAN_DEVELOPMENT <- read_data('A168:O200', Degree_of_Human_Development, 'LOW HUMAN DEVELOPMENT' )

HDI <- bind_rows(VERY_HIGH_HUMAN_DEVELOPMENT,HIGH_HUMAN_DEVELOPMENT,MEDIUM_HUMAN_DEVELOPMENT,LOW_HUMAN_DEVELOPMENT)
```


#Reading the cleaned "csv" file and saving the file with the name of "HDIData.csv" in folder (documents->data).

```{r}
write_csv(HDI, "data/HDIData.csv")
```

